image: ubuntu:18.04

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

build:
  script:
    - lftp -e "set ssl:verify-certificate no; open $FTP_SERVER; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X ./* --reverse --verbose --delete ./ public_html/; bye"

