name: Deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Deploy to website through ftp
      run: |
        apt-get update,
        apt-get -qq install git-ftp,
        git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_SERVER
