name: Deployment

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to website through ftp
      uses: sebastianpopp/git-ftp-action@releases/v2
      env:
	 FTP_SERVER: "files.000webhost.com"
	 FTP_USERNAME: $FTP_USERNAME
	 FTP_PASSWORD: $FTP_PASSWORD
