name: Deployment

on: [push]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: FTP-Deploy-Action
      uses: sebastianpopp/git-ftp-action@releases/v2
      with:
        url: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        syncroot: public_html
