name: Deployment

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to website through ftp
      uses: sebastianpopp/git-ftp-action@releases/v2
      with:
	 url: "${{ secrets.FTP_SERVER }}"
	 user: "${{ secrets.FTP_USERNAME }}"
	 password: "${{ secrets.FTP_PASSWORD }}"
