name: Deployment

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to website through ftp
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
	 FTP_SERVER: "files.000webhost.com"
	 FTP_USERNAME: $FTP_USERNAME
	 FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
