name: Deployment

on: [push]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to website through ftp
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
	 FTP_SERVER: "files.000webhost.com"
	 FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
	 FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
