name: Deployment

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to website through ftp
      uses: sebastianpopp/git-ftp-action@releases/v2
      env:
	 FTP_SERVER: ${ secrets.FTP_SERVER }
	 FTP_USERNAME: ${ secrets.FTP_USERNAME }
	 FTP_PASSWORD: $secrets.FTP_PASSWORD
